/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author isidro
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnA_Lineal = new javax.swing.JButton();
        btnA_Multiplicativo = new javax.swing.JButton();
        btnA_NoLineal = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        btnA_Aditivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnA_Lineal.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnA_Lineal.setText("LINEAL");
        btnA_Lineal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA_LinealActionPerformed(evt);
            }
        });

        btnA_Multiplicativo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnA_Multiplicativo.setText("MULTIPLICATIVO");
        btnA_Multiplicativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA_MultiplicativoActionPerformed(evt);
            }
        });

        btnA_NoLineal.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnA_NoLineal.setText("NO LINEAL");
        btnA_NoLineal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA_NoLinealActionPerformed(evt);
            }
        });

        lblInfo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblInfo.setText("Seleccione el metodo de generacion de numeros aleatorios");

        btnA_Aditivo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnA_Aditivo.setText("CUADRATICO");
        btnA_Aditivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA_AditivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnA_Lineal, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(btnA_Multiplicativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnA_NoLineal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnA_Aditivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(169, 169, 169))
                    .addComponent(lblInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfo)
                .addGap(18, 18, 18)
                .addComponent(btnA_Lineal)
                .addGap(26, 26, 26)
                .addComponent(btnA_Multiplicativo)
                .addGap(27, 27, 27)
                .addComponent(btnA_NoLineal)
                .addGap(27, 27, 27)
                .addComponent(btnA_Aditivo)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnA_LinealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA_LinealActionPerformed
        A_Lineal AL = new A_Lineal();
        AL.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnA_LinealActionPerformed

    private void btnA_MultiplicativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA_MultiplicativoActionPerformed
        A_Multiplicativo AM = new A_Multiplicativo();
        AM.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnA_MultiplicativoActionPerformed

    private void btnA_NoLinealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA_NoLinealActionPerformed
        A_NoLineal ANL = new A_NoLineal();
        ANL.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnA_NoLinealActionPerformed

    private void btnA_AditivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA_AditivoActionPerformed
        A_Cuadratico AC = new A_Cuadratico();
        AC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnA_AditivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA_Aditivo;
    private javax.swing.JButton btnA_Lineal;
    private javax.swing.JButton btnA_Multiplicativo;
    private javax.swing.JButton btnA_NoLineal;
    private javax.swing.JLabel lblInfo;
    // End of variables declaration//GEN-END:variables
}
